apiVersion: v1
kind: Pod
metadata:
  name: devops11-httpd-node-selector
  namespace: test
  labels:
    env: prod
    tier: web
spec:
  containers:
  - name: my-httpd
    image: httpd
    ports:
    - containerPort: 80
  nodeSelector:
    tier: app
