apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-dynamic
  labels:
    app: mysql
    tier: database
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
