apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-example-no-replicas
  namespace: dev
  labels:
    app: nginx-rs-pod
spec:
#  replicas: 6 
  selector:
    matchLabels:
      purpose: example-1
  template:
    metadata:
      labels:
        purpose: example-1
        type: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2

