apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-recreate
  namespace: dev
  labels:
    app: nginx-rs-pod
spec:
  replicas: 2
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      purpose: example-1
  template:
    metadata:
      labels:
        purpose: example-1
        type: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.16.1

