apiVersion: v1
kind: Pod
metadata:
  name: with-node-antiffinity-hard-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: tier
            operator: NotIn
            values:
            - web
  containers:
  - name: with-node-affinity
    image: httpd

