apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngicnx-deployment-maxsugre
  namespace: prod
  labels:
    app: nginx-deploy
spec:
  # 1. How many copies of each pod do we want?
  replicas: 4  # replicatset
  # 2. How do want to update the pods?
  strategy: 
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 50%
       maxUnavailable: 50%
  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: example
  
  # This template field is a regular pod configuration nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: example
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.1
          resources:
            requests:
              memory: 10Mi
              cpu: 2m
            limits:
              memory: 200Mi
              cpu: 100m





