apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: prod
spec:
  hard:
    requests.cpu: "10m"
    requests.memory: 100Mi
    limits.cpu: "500m"
    limits.memory: 1Gi

