apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange-demo
  namespace: prod
spec:
  limits:
  - default: # default limits set for container , it shouldn't be more than max values
      cpu: "40m"
      memory: 30Mi
    defaultRequest:
      cpu: "30m"
      memory: 25Mi
    max:
      cpu: "100m"
      memory: 100Mi
    min:
      cpu: "15m"
      memory: 15Mi
    type: Container
