apiVersion: v1
kind: Pod
metadata:
  name: devops11-httpd-2
  namespace: prod
spec:
  containers:
  - name: my-httpd
    image: httpd
    resources:
      requests:
        cpu: 15m
        memory: 100Mi
      limits:
        cpu: 20m
        memory: 100Mi
