apiVersion: v1
kind: ReplicationController
metadata:  # Replication controller 
  name: rc-example-2
  labels:
    app: myapp
    type: web
spec:  #Replication controller
  #replicas: 3
  selector:
    app: nginx-web
  template:
    metadata:  # POD 
      name: nginx-pod
      labels:
        app: nginx-web
    spec: # POD
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
