apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-2
  labels:
    app: myapp
    type: web   
spec:
  replicas: 3
  selector:
    app: nginx-rs-pod
  template:
    metadata:
      labels:
        app: nginx-rs-pod
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
