apiVersion: v1
kind: Pod
metadata: 
  name: httpd-pod-tcpsocket
  labels:
    app: httpd-web
spec: 
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80
    livenessProbe:
      tcpSocket:
        port: 80
