apiVersion: v1
kind: Pod
metadata: 
  name: httpd-pod-readiness-fail
  labels:
    app: httpd-web
spec: 
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 81
