apiVersion: v1
kind: ReplicationController
metadata:  # Replication controller 
  name: naginx-rc-example-1
  labels:
    app: myapp
    type: web
spec:  #Replication controller
  template:
    metadata:  # POD 
      name: nginx-pod
      labels:
        app: nginx-web
    spec: # POD
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
  replicas: 10
  selector:
    app: nginx-web
