apiVersion: v1
kind: ReplicationController
metadata:
  name: devops11-httpd
spec:
 replicas: 3
 selector:
   type: web
 template:
   metadata:
     name: devops11-httpd
     labels:
       type: web
   spec:
     containers:
     - name: my-httpd
       image: httpd
