apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-prod
  labels:
    app: myapp
    type: web   
spec:
  template:
    metadata:
      labels:
        app: nginx-rs-pod
        environment: prod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs-pod
