apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-1
  labels:
    app: myapp
    type: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-rs-pod
    matchExpressions:
      - {key: environment, operator: In ,values: [dev,prod]} # environment=dev ,environement=prod
  template:
    metadata:
      labels:
        app: nginx-rs-pod
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80 
