apiVersion: v1
kind: Pod
metadata:
  name: nginx-without-effect
  labels:
    env: taint-toleration
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "tier"
    operator: "Equal"
    value: "web"
    effect: 
  nodeSelector:
    tier: web
