apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-taint-preferno-schedule-1
  labels:
    env: prod
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    tier: web
