apiVersion: v1
kind: Pod
metadata: 
  name: jenkins-pod-1
  namespace: jenkins
  labels:
    app: jenkins
spec: 
  containers:
  - name: jenkins
    image: jenkins:2.60.3
    ports:
    - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 2
      periodSeconds: 10

