apiVersion: v1 # in which version the resource has been developed.
kind: Pod  # this indicate the kubernetes resource type
metadata:
  name: my-jenkins-1
  namespace: dev
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    resources:
      requests:
        memory: "100Mi"
        cpu: "50m"
      limits:
        memory: "500Mi"
        cpu: "100m"
