apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-example
  namespace: prod
  labels:
    app: nginx-deploy
spec:
  # 1. How many copies of each pod do we want?
    replicas: 4  # replicatset
  # 2. How do want to update the pods?
  # strategy: Recreate
  # 3. Which pods are managed by this deployment?
    selector:
     # This must match the labels we set on the pod!
     matchLabels:
      deploy: example-1
    template:
     metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: example-1
     spec:
      containers:
      - name: nginx
        image: nginx:1.14.1
