apiVersion: v1
kind: Pod
metadata:
  name: devops11-httpd-config-test
  namespace: test
spec:
  containers:
  - name: my-httpd
    image: httpd
    volumeMounts:
      - name: httpd-conf-vol
        mountPath: /usr/local/apache2/conf/httpd.conf
        subPath: httpd.conf
  volumes:
    - name: httpd-conf-vol
      configMap:
        name: my-httpd-conf
