apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo-daemonset
  namespace: qa-test
spec:
  selector:
    matchLabels:
       app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: monitoring
          image: busybox
          command: ['sh', '-c', 'echo devops11 && sleep 300' ]
